language: ruby

dist: xenial

rvm:
  - 2.6

services:
  - xvfb

branches:
  only:
    - master

env:
  global:
    - MAGICK_CONFIGURE_PATH=$HOME/.config/ImageMagick
  jobs:
    - REDMINE_VER=4.1.1
    - REDMINE_VER=4.0.7
    - REDMINE_VER=master

jobs:
  allow_failures:
    - env: REDMINE_VER=master

addons:
  postgresql: "9.4"
  chrome: stable

before_install:
  # Allow imagemagick to read PDF files
  - echo $MAGICK_CONFIGURE_PATH
  - mkdir $MAGICK_CONFIGURE_PATH
  - echo '<policymap>' > $MAGICK_CONFIGURE_PATH/policy.xml
  - echo '<policy domain="coder" rights="read | write" pattern="PDF" />' >> $MAGICK_CONFIGURE_PATH/policy.xml
  - echo '</policymap>' >> $MAGICK_CONFIGURE_PATH/policy.xml
  - sudo rm /etc/ImageMagick-6/policy.xml

install: "echo skip bundle install"

before_script:
  - sudo apt-get update
  - sudo apt-get install -y ghostscript
  - psql -c 'create database travis_ci_test;' -U postgres
  - gem install chromium
  - wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_templates
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - cp spec/support/* $TESTSPACE/
  - bash -x ./travis.sh
